### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Teufelchen1** [kosmas12/My-code-stuff#2]
Hi 👋 

Whats your reason for choosing `__uint64_t` as type in your [Fibonacci](https://github.com/kosmas12/My-code-stuff/blob/master/Fibonacci%20Sequnce%20(C)/main.c)?
There is a full path, including your username, in your Makefile for the calculator.
The Makefile in the Mandelbrot is written with a lowercase 'm'. Unusual. 
The Mandelbrot is based on a fork, no proper credit is given. 
There are two README in the Mandelbrot project.
The screenshot is not from xqemu :) 

Happy hacking!

**Comment by kosmas12** [comment]
1) My reason for choosing __uint64_t is to be able to output 64 bit numbers, since the Fibonacci sequence got too big for 32 bit numbers with that many times that I run the loop. If someone runs it less times, though, he/she can decrease the number bits.
2) That's because I didn't know how to make a Makefile use the user path yet. Fixed.
3) It's personal preference (also the base code used that)
4) Kind of fixed?
5) Fixed
6) Fixed

**Comment by Teufelchen1** [comment]
Not sure why you marked 2. & 6. as fixed? Rest looks good.

**Comment by kosmas12** [comment]
In #2 I forgot to fix the master branch. #6 is on nxdk branch because I think it fits more there.

**Comment by Teufelchen1** [comment]
great. 👍
